// <auto-generated />
namespace SannaComerce.Infrastructure.Repositories.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kapoc2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kapoc2));
        
        string IMigrationMetadata.Id
        {
            get { return "201711270320124_kapoc2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
